[package]
name    = "prolens_example"
version = "0.1.0"
edition = "2024"

[dependencies]
pcap       = "2.2.0"
etherparse = "0.13.0"
libc       = "0.2"
ctrlc      = "3.4.2"
tmohash = { path = "./tmo_hash", version = "0.1.0"}
protolens = { path = "../protolens/", version = "0.2.0"}
